#!/bin/bash

# Set the log file
LOGFILE="$PATCHDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1

echo "PATCHDIR is set to: $PATCHDIR"

cd "$PATCHDIR"

# Default the screen-size option to Full (4) instead of the engine
# default of M (1). Fresh installs have no stored options.
if [ -f Scripts/Rejuv/Settings.rb ]; then
    sed -i 's/^\(\s*DEFAULTSCREENZOOM\s*=\s*\).*/\14.0/' Scripts/Rejuv/Settings.rb
fi

# Use ffmpeg to lower the gif's framerate to reduce ram usage spike
./utils/ffmpeg -i Graphics/Titles/splash.gif -vf "fps=15,scale=480:-1:flags=lanczos" -y Graphics/Titles/temp_splash.gif
mv Graphics/Titles/temp_splash.gif Graphics/Titles/splash.gif
