#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="patchlog.txt"
LOGERR="patcherr.txt"

# Redirect output and error to the log file
rm -f "$GAMEDIR/$LOGERR"
> "$GAMEDIR/$LOGFILE" && exec > >(tee "$GAMEDIR/$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/assets"
export DATAFILE="koboo_prologue.port"
export TMPDIR="$GAMEDIR/tmp"

prepare_system() {
    # Test for commands: python, zip
    PYTHON=$(command -v python3)
    if [ -z "$PYTHON" ]; then
        echo "Missing Python!"
        return 1
    fi
    
    # Mount the GMToolkit runtime
    TOOLKIT="$HOME/gmtoolkit"
    RUNTIME="$controlfolder/libs/gmtoolkit.squashfs"
    if [ -f "$RUNTIME" ]; then
        $ESUDO mkdir -p "$TOOLKIT"
        $ESUDO umount "$TOOLKIT" 2>/dev/null || true
        $ESUDO mount "$RUNTIME" "$TOOLKIT"
    else
        echo "This port requires the GMToolkit runtime. Please download it."
        return 1
    fi

    # Mount the dotnet runtime
    DOTNETDIR="$HOME/mono"
    DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
    if [ -f "$DOTNETFILE" ]; then
        $ESUDO mkdir -p "$DOTNETDIR"
        $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
        $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
    else
        echo "This port requires the Dotnet runtime. Please download it."
        return 1
    fi
    
    # Attempt to get SAVEDIR from gmloader.json using jq
    if command -v jq >/dev/null 2>&1; then
        SAVEDIR=$(jq -r '.save_dir // empty' "$GAMEDIR/gmloader.json" 2>/dev/null)
    else
        SAVEDIR="$GAMEDIR/saves"
    fi
    
    # Exports
    export PYTHON
    export SAVEDIR
    export PATH="$DOTNETDIR:$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
    export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"

    # These exports help dotnet save memory and hopefully eliminate oomkill issues during patching
    export DOTNET_gcServer=0
    export DOTNET_gcLatencyLevel=SustainedLowLatency
    export DOTNET_GCHighMemPercent=50
}

prepare_files() {
    mkdir -p "$SAVEDIR"
    
    # Delete excess files
    find "$DATADIR" -type f \( \
        -name "*.gitkeep" -o -name "*.exe" -o -name "*.dll" -o -name "*.hashdb" -o \
        -name "*.html" -o -name "*.ico" -o -name "*.lnk" -o -name "*.msg" -o -name "*.zip" \
    \) -exec rm -f {} \;
    
    # Delete excess folders
    rm -rf "$DATADIR/GMLive"

    # Move splash file if it exists
    if [ -f "$DATADIR/splash.png" ]; then
        mv "$DATADIR/splash.png" "$GAMEDIR/splash.png"
    fi
}

# Apply patch
xdelta_patch() {
    FILESUM=$(md5sum "$DATADIR/data.win" | awk '{ print $1 }')
    STEAMSUM="979564ec8e7ea1f560930a24a4a499dd"

        if [ "$FILESUM" = "$STEAMSUM" ]; then
            output=$("$controlfolder/xdelta3" -d -s "$GAMEDIR/assets/data.win" -f "$GAMEDIR/tools/koboo_prologue.xdelta" "$DATADIR/data2.win" 2>&1)
            if [ $? -eq 0 ]; then
                echo "Patch applied successfully"
                echo "$output"
                rm -f "$DATADIR/data.win" && mv "$DATADIR/data2.win" "$DATADIR/data.win"
            else
                echo "Unable to apply xdelta: $output"
                return 1
            fi
        else
            echo "MD5 does not match target, cannot apply xdelta."
            return 1
        fi
}

# Externalize game textures with compression
dump_textures() {
    # Purge cache before operations
    rm -rf "$SAVEDIR/textures"
    rm -rf "$TMPDIR/"*
    
    # Begin texture operations
    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
        dump "$DATADIR/data.win" \
        -e "$DATADIR/textures" "$DATADIR/data2.win"

    if [ $? -ne 0 ]; then
        echo "[DOTNET]: Texture dumping failed to apply."
        return 1
    else
        rm -f "$DATADIR/data.win" && mv "$DATADIR/data2.win" "$DATADIR/data.win"
        mv "$DATADIR/textures" "$SAVEDIR/textures"
        if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]; then
            rm -rf "$TMPDIR"/*
        fi
    fi
}

# Compress audio files inside datafile and audiogroups
compress_audio() {
    # Purge cache before operations
    rm -rf "$TMPDIR/"*

    # Run the compression tool
    echo "Running GMTools on data and audiogroups."
    $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/data.win"

    if [ $? -eq 0 ]; then
        echo "Compression completed successfully."
        mv "$TMPDIR/"* "$DATADIR"
        echo "Moved compressed files to $DATADIR."
        rm -rf "$TMPDIR"
        echo "Temporary directory $TMPDIR removed."
        echo "Audio compression applied successfully."
    else
        # Failure
        echo "Audio compression failed."
        if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]; then
            rm -rf "$TMPDIR"/*
        fi
        return 1
    fi
}

# Zip it all into the .port file
zip_archive() {
    [ -f "$DATADIR/data.win" ] && mv "$DATADIR/data.win" "$DATADIR/game.droid"
    if "$controlfolder/7zzs.${DEVICE_ARCH}" a -tzip -aoa -mx=0 "$GAMEDIR/$DATAFILE" "$DATADIR"; then
        rm -rf "$DATADIR"/*
    else
        echo "Failed to create $DATAFILE."
        return 1
    fi
}

# Cleanup
cleanup() {
    rm -rf "$TMPDIR"
    $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
    $ESUDO umount "$TOOLKIT" 2>/dev/null || true
}

process_game() {
    echo "Preparing system..."
    prepare_system || { cleanup; return 1; }
    echo "Preparing game..."
    prepare_files || { cleanup; return 1; }
    echo "Applying xdelta..."
    xdelta_patch || { cleanup; return 1; }
    echo "Compressing audio..."
    compress_audio || { cleanup; return 1; }
    echo "Externalizing textures..."
    dump_textures || { cleanup; return 1; }
    echo "Finishing up..."
    zip_archive || { cleanup; return 1; }
}

# Call the function
if ! process_game; then
    echo "Patching process failed!"
    mv "$LOGFILE" "$LOGERR"
else
    echo "Patching process complete!"
fi

# Always run cleanup at the end
cleanup
